@startuml UC03_VOPC
class CourseQueryUI <<Boundary>> {
    +onSearch()
    +renderList()
}
class CourseSearchController <<Control>> {
    +search()
}
interface ExternalDBInterface <<Boundary>> {
    +pullCourseInfo()
    +pushData()
}
class Course <<Entity>> {
    -code: String
    -name: String
    -credits: Float
    -teacher: String
}

CourseQueryUI ..> CourseSearchController
CourseSearchController ..> ExternalDBInterface
CourseSearchController ..> Course
@enduml
