@startuml UC06_VOPC
class GradeEntryUI <<Boundary>> {
    +inputGrades()
}
class GradeController <<Control>> {
    +saveGrades()
}
class GradeRecord <<Entity>> {
    -sid: String
    -cid: String
    -dailyScore: Float
    -examScore: Float
    -finalScore: Float
    +calculateFinalScore()
}

GradeEntryUI ..> GradeController
GradeController ..> GradeRecord
@enduml
