@startuml UC06_Sequence
actor Teacher
boundary GradeEntryUI
control GradeController
entity GradeRecord
entity Course

Teacher -> GradeEntryUI : 录入/修改成绩
activate GradeEntryUI
GradeEntryUI -> GradeController : saveGrades(cid, gradeData)
activate GradeController
loop for each student
    GradeController -> GradeRecord : updateScore(sid, cid, scores)
    activate GradeRecord
    GradeRecord -> GradeRecord : calculateFinalScore()
    GradeRecord --> GradeController : success
    deactivate GradeRecord
end
GradeController --> GradeEntryUI : notifySaveSuccess()
deactivate GradeController
GradeEntryUI --> Teacher : 提示成功
deactivate GradeEntryUI
@enduml
