@startuml UC07_VOPC
class CourseManagementUI <<Boundary>> {
    +onEdit()
    +onPublish()
}
class CourseInfoController <<Control>> {
    +publishCourseInfo()
}
class Course <<Entity>> {
    -cid: String
    -syllabus: String
    -plan: String
}
class ExternalDBInterface <<Boundary>> {
    +pushData()
}

CourseManagementUI ..> CourseInfoController
CourseInfoController ..> Course
CourseInfoController ..> ExternalDBInterface
@enduml
