@startuml UC08_Sequence
actor Admin
boundary UserManagementUI
control UserOpsController
entity User
entity Student
entity Teacher

Admin -> UserManagementUI : 添加/修改用户数据
activate UserManagementUI
UserManagementUI -> UserOpsController : saveUserData(data)
activate UserOpsController
UserOpsController -> User : upsert(data)
alt Case: Student
    UserOpsController -> Student : updateAcademicInfo(data)
else Case: Teacher
    UserOpsController -> Teacher : updateProfessionalInfo(data)
end
UserOpsController --> UserManagementUI : notifySuccess()
deactivate UserOpsController
UserManagementUI --> Admin : 显示保存成功
deactivate UserManagementUI
@enduml
